//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderExecutionControl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderExecutionControlEntities : DbContext
    {
        private static OrderExecutionControlEntities context;

        public OrderExecutionControlEntities()
            : base("name=OrderExecutionControlEntities")
        {
        }
        public static OrderExecutionControlEntities GetContext()
        {
            if (context == null)
                context = new OrderExecutionControlEntities();

            return context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<commission> commission { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<position> position { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<subtask> subtask { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
