//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderExecutionControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class subtask
    {
        public int code_subtask { get; set; }
        public string name_subtask { get; set; }
        public string text_subtask { get; set; }
        public Nullable<System.DateTime> date_of_registration_subtask { get; set; }
        public Nullable<System.DateTime> start_date_subtask { get; set; }
        public Nullable<System.DateTime> end_date_subtask { get; set; }
        public int code_commission { get; set; }
        public int code_employee { get; set; }
        public int code_status { get; set; }
        public string attached_file { get; set; }
    
        public virtual commission commission { get; set; }
        public virtual employee employee { get; set; }
        public virtual status status { get; set; }
    }
}
